feat: 添加 runc 补丁

diff --git a/.github/workflows/build-binaries.yml b/.github/workflows/build-binaries.yml
--- a/.github/workflows/build-binaries.yml
+++ b/.github/workflows/build-binaries.yml
@@ -19,6 +19,10 @@ jobs:
         run: |
           PACKAGE_VERSION=v$(curl -sSL https://github.com/docker/containerd-packaging/raw/main/debian/changelog | head -n 1 | grep -oP '\(\K[^\)]+' | cut -d'-' -f1)
           BINARIES_VERSION=$(curl -s "https://api.github.com/repos/containerd/containerd/releases/latest" | jq -r .tag_name)
+          if [ -z "$PACKAGE_VERSION" ] || [ "$PACKAGE_VERSION" == "null" ] || [ -z "$BINARIES_VERSION" ] || [ "$BINARIES_VERSION" == "null" ]; then
+            echo "Failed to get version"
+            exit 1
+          fi
           sed -i "s@CONTAINERD_VERSION=.*@CONTAINERD_VERSION=${PACKAGE_VERSION}@g" build-containerd.sh
           sed -i "s@ARG CONTAINERD_VERSION=.*@ARG CONTAINERD_VERSION=${BINARIES_VERSION}@g" binaries/Dockerfile
           echo "CONTAINERD_VERSION=${BINARIES_VERSION}" >> $GITHUB_ENV
diff --git a/.github/workflows/build-packages.yml b/.github/workflows/build-packages.yml
--- a/.github/workflows/build-packages.yml
+++ b/.github/workflows/build-packages.yml
@@ -18,6 +18,10 @@ jobs:
         id: get-version
         run: |
           PACKAGE_VERSION=v$(curl -sSL https://github.com/docker/containerd-packaging/raw/main/debian/changelog | head -n 1 | grep -oP '\(\K[^\)]+' | cut -d'-' -f1)
+          if [ -z "$PACKAGE_VERSION" ] || [ "$PACKAGE_VERSION" == "null" ]; then
+            echo "Failed to get version"
+            exit 1
+          fi
           sed -i "s@CONTAINERD_VERSION=.*@CONTAINERD_VERSION=${PACKAGE_VERSION}@g" build-containerd.sh
           sed -i "s@ARG CONTAINERD_VERSION=.*@ARG CONTAINERD_VERSION=${PACKAGE_VERSION}@g" binaries/Dockerfile
           echo "CONTAINERD_VERSION=${PACKAGE_VERSION}" >> $GITHUB_ENV
